#!/usr/bin/env bash
# Regenerates src/sys/bindings.rs (raw FFI declarations for libghostty-vt)
# from the headers in the vendored ghostty submodule. Needs bindgen-cli
# (`cargo install bindgen-cli`) and libclang. The output is committed, so
# normal builds don't need either.
set -euo pipefail
here="$(cd "$(dirname "$0")/.." && pwd)"
bindgen "$here/vendor/ghostty/include/ghostty/vt.h" \
  --output "$here/src/sys/bindings.rs" \
  --rust-target 1.85 \
  --rust-edition 2024 \
  --use-core \
  --merge-extern-blocks \
  --no-doc-comments \
  --allowlist-function 'ghostty_.*' \
  --allowlist-type 'Ghostty.*' \
  --allowlist-var 'GHOSTTY_.*' \
  --default-enum-style consts \
  --with-derive-default \
  --raw-line '// Generated by native/scripts/gen-bindings.sh from the libghostty-vt headers. Do not edit.' \
  -- -I"$here/vendor/ghostty/include" -DGHOSTTY_STATIC
echo "wrote $here/src/sys/bindings.rs ($(wc -l < "$here/src/sys/bindings.rs") lines)"
