//! Raw FFI declarations for libghostty-vt, generated by
//! `scripts/gen-bindings.sh`. Only the `vt` module uses these.
#![allow(
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    dead_code,
    unsafe_code,
    unsafe_op_in_unsafe_fn,
    unnecessary_transmutes,
    clippy::all
)]

include!("bindings.rs");
